### PR TITLE
Tracking request progress

### PR DESCRIPTION
**Pull request by VasuSankaran**
While investigating recent alerts raised due to request latency, it seemed useful to add request progress status to trace. This PR adds the framework support. Later services code will be instrumented to record progression.

---
This change is [Reviewable](https://reviewable.io/reviews/spirentorion/luddite/64)

### CODE REVIEW

**Comment by djoyner** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[body.go, line 49 at r2](https://reviewable.io:443/reviews/spirentorion/luddite/64#-KwfO7V7MbubzpfzU0vc:-KwfO7V7MbubzpfzU0vd:bjwjwxq) ([raw file](https://github.com/spirentorion/luddite/blob/1b0afd85b906759d33dff4b2be27dca56e039a6f/body.go#L49)):*
> ```Go
> 	defer func() {
> 		SetContextRequestProgress(req.Context(), "luddite.ReadRequest")
> 	}()
> ```

Maybe just me, but if I'm looking at trace data I would expect that `req_progress` would indicate that execution has reached this point, not that it had proceeded _past_ this point. What do you think?

Shouldn't there also be other progress indications set within `luddite`, e.g. when the handler details are first allocated, as the middleware layers run, and then when the router dispatches to the resource methods.

---

*[context.go, line 128 at r2](https://reviewable.io:443/reviews/spirentorion/luddite/64#-KwfNtv-N0JcDAn_ThbO:-KwfNtv-N0JcDAn_ThbP:bacji5t) ([raw file](https://github.com/spirentorion/luddite/blob/1b0afd85b906759d33dff4b2be27dca56e039a6f/context.go#L128)):*
> ```Go
> 	}
> 	return
> }
> ```

Code looks good but please add doc strings for the three functions above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/spirentorion/luddite/64)*

**Comment by VasuSankaran** [comment]
Bump

**Comment by djoyner** [comment]
Reviewed 6 of 7 files at r3.
Review status: 6 of 7 files reviewed at latest revision, 6 unresolved discussions.

---

*[body.go, line 89 at r3](https://reviewable.io:443/reviews/spirentorion/luddite/64#-Kwg5mUm-q5xtdDpLl93:-Kwg5mUm-q5xtdDpLl94:b-wjzjw9) ([raw file](https://github.com/spirentorion/luddite/blob/2a3318bb4084b73260c4ed3a9cb7ee372c5a016d/body.go#L89)):*
> ```Go
> }
> 
> func WriteResponse(rw http.ResponseWriter, ctx context.Context, status int, v interface{}) (err error) {
> ```

Luddite is used by many projects, and I would prefer to avoid this breaking API change. See below for suggestions.

---

*[bottom.go, line 180 at r3](https://reviewable.io:443/reviews/spirentorion/luddite/64#-Kwg5y0AW4yhMZT5IM8M:-Kwg5y0AW4yhMZT5IM8N:b-i78am) ([raw file](https://github.com/spirentorion/luddite/blob/2a3318bb4084b73260c4ed3a9cb7ee372c5a016d/bottom.go#L180)):*
> ```Go
> 	})
> 
> 	SetContextRequestProgress(ctx0, "Bottom", "HandleHTTP", "handler details set")
> ```

Consider initializing directly when `handlerDetails` is allocated one line above rather than incurring the overhead of context lookup.

---

*[context.go, line 128 at r2](https://reviewable.io:443/reviews/spirentorion/luddite/64#-KwfNtv-N0JcDAn_ThbO:-Kwg67jgy-v2yWhpASBb:b-kw6v6h) ([raw file](https://github.com/spirentorion/luddite/blob/1b0afd85b906759d33dff4b2be27dca56e039a6f/context.go#L128)):*
<details><summary><i>Previously, djoyner (David Joyner) wrote…</i></summary><blockquote>

Code looks good but please add doc strings for the three functions above.
</blockquote></details>

Still open

---

*[context.go, line 123 at r3](https://reviewable.io:443/reviews/spirentorion/luddite/64#-Kwg6K40Fl1dyY4A67J-:-Kwg6K40Fl1dyY4A67J0:b-gazx8a) ([raw file](https://github.com/spirentorion/luddite/blob/2a3318bb4084b73260c4ed3a9cb7ee372c5a016d/context.go#L123)):*
> ```Go
> }
> 
> func SetContextRequestProgress(ctx context.Context, typeName, funcName, stage string) {
> ```

Seeing this get used other places, would suggest that `typeName` -> `pkgName`. For example:

`"luddite", "FormatNegotiator.HandleHTTP", "begin"`
`"luddite", "AddListRoute", "begin"`
etc...

---

*[resource.go, line 60 at r3](https://reviewable.io:443/reviews/spirentorion/luddite/64#-Kwg6sTUcod3Og-PZP6N:-Kwg6sTVokck63wWZwq-:bt7t1bh) ([raw file](https://github.com/spirentorion/luddite/blob/2a3318bb4084b73260c4ed3a9cb7ee372c5a016d/resource.go#L60)):*
> ```Go
> 	router.GET(basePath, func(rw http.ResponseWriter, req *http.Request, params httprouter.Params) {
> 		SetContextRequestProgress(req.Context(), "Router", "List", "begin")
> 		status, v := r.List(req)
> ```

As mentioned above, instead of making a breaking change to `WriteResponse`, simply add a progress call here: `"luddite", "AddListRoute", "write"`

---

*[version.go, line 25 at r3](https://reviewable.io:443/reviews/spirentorion/luddite/64#-Kwg7G6MiVpwI2V5ymto:-Kwg7G6MiVpwI2V5ymtp:bgkhkrl) ([raw file](https://github.com/spirentorion/luddite/blob/2a3318bb4084b73260c4ed3a9cb7ee372c5a016d/version.go#L25)):*
> ```Go
> func (v *Version) HandleHTTP(rw http.ResponseWriter, req *http.Request, next http.HandlerFunc) {
> 	ctx := req.Context()
> 	SetContextRequestProgress(ctx, "Version", "HandleHTTP", "begin")
> ```

Since the route-oriented methods set progress right before resource handlers are invoked, I think we can dispense with this (as well as with decorating every single resource handler throughout most projects).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/spirentorion/luddite/64)*

**Comment by VasuSankaran** [comment]
Bump

**Comment by djoyner** [comment]
:lgtm:

---

Reviewed 5 of 7 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/spirentorion/luddite/64#-:-KwgywHMzy4VB0SS6YYP:bnfp4nl)*

**Pull request merged**
